version: ">= 1.0.0"
language: node_js
node_js:
  - "10"
os: linux
dist: xenial
arch: amd64
cache:
  yarn: true
  directories:
    - node_modules
jobs:
  include:
    - stage: test
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash
        - export PATH="$HOME/.yarn/bin:$PATH"
      install:
        - yarn --frozen-lockfile
      before_script:
        - yarn run clean:component
        - yarn run build:component
      script:
        - yarn run test:ci
    - stage: release
      if: "(tag =~ /^v3/) AND (NOT (type IN (pull_request)))"
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash
        - export PATH="$HOME/.yarn/bin:$PATH"
      install:
        - yarn --frozen-lockfile
      before_script:
        - yarn run clean:component
      script:
        - yarn run build:component
      before_deploy:
        - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
      deploy:
        provider: script
        skip_cleanup: true
        script: "yarn run publish"
        on:
          tags: true
          repo: NervJS/disscode-lib
    - stage: deploy
      if: "(branch = master) AND (NOT (type IN (pull_request)))"
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash
        - export PATH="$HOME/.yarn/bin:$PATH"
      install:
        - yarn --frozen-lockfile
      before_script:
        - yarn run clean
      script:
        - yarn run build
      after_script:
        - cd packages/disscode-lib-docs/dist
        - git init
        - git add -A
        - git commit -m "Update Document"
        - git push --force --quiet "https://${GITHUB_TOKEN}@${GH_REF}" master:gh-pages
env:
  global:
    - GH_REF=github.com/NervJS/disscode-lib.git
